---

kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "ssh-jump"
  annotations:
    app.kubernetes.io/name: "ssh-jump"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ssh-jump"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ssh-jump"
    spec:
      imagePullSecrets:
        - name: "infra-artifact-repository"
      containers:
        - name: "ssh-jump"
          image: "ghcr.io/agni-sairent/ssh-jump:latest"
          imagePullPolicy: "Always"
          securityContext:
            seccompProfile:
              type: "RuntimeDefault"
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - "ALL"
          env:
            - name: "USER_PUBLIC_KEY"
              value: "ssh-ed25519 <public-key-here>"
          ports:
            - containerPort: 22
              name: "ssh"